// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB09bPSh9-zX-7ayn8_fPwxhzdqY9llmFw',
    appId: '1:438267258839:web:d7377bb01b9f265d874d92',
    messagingSenderId: '438267258839',
    projectId: 'kutuphane-otomasyon-fc804',
    authDomain: 'kutuphane-otomasyon-fc804.firebaseapp.com',
    storageBucket: 'kutuphane-otomasyon-fc804.appspot.com',
    measurementId: 'G-5Z2P1FTGE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASAqQVGk1CxH1IQhaKTKRCt_1kIRzTBJU',
    appId: '1:438267258839:android:217967c30b1e0044874d92',
    messagingSenderId: '438267258839',
    projectId: 'kutuphane-otomasyon-fc804',
    storageBucket: 'kutuphane-otomasyon-fc804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhDV9GDWkK_5LcWtEdGV8l2qC0pZ63XfY',
    appId: '1:438267258839:ios:028da1e3f7b5fade874d92',
    messagingSenderId: '438267258839',
    projectId: 'kutuphane-otomasyon-fc804',
    storageBucket: 'kutuphane-otomasyon-fc804.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyonu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhDV9GDWkK_5LcWtEdGV8l2qC0pZ63XfY',
    appId: '1:438267258839:ios:0c7d4d16bb8aa14a874d92',
    messagingSenderId: '438267258839',
    projectId: 'kutuphane-otomasyon-fc804',
    storageBucket: 'kutuphane-otomasyon-fc804.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyonu.RunnerTests',
  );
}
